name: Deploy prod
on:
    push:
        branches:
            - prod
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            - name: Finish
              run: echo "Deploy prod done"
